workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: Codemagic

    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        provisioning_profiles:
          - mindgarden_profile

    scripts:
      - name: Set up code signing
        script: |
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles

      - name: Get Flutter packages
        script: |
          cd mind_garden
          flutter pub get

      - name: Build IPA
        script: |
          cd mind_garden
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - mind_garden/build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true