workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60

    environment:
      flutter: stable

    scripts:
      - name: Get Flutter packages
        script: |
          cd mind_garden
          flutter pub get

      - name: Build iOS (no signing)
        script: |
          cd mind_garden
          flutter build ios --release --no-codesign

    artifacts:
      - mind_garden/build/ios/iphoneos/*.app